common:
  - .flake8
  - .gitignore
  - .pre-commit-config.yaml
  - environment.yml
  - LICENSE.txt
  - Makefile
  - pyproject.toml
  - requirements/dev-lint.in
  - requirements/dev.in
  - requirements/dev.txt
  - requirements/prod.in
  - requirements/prod.txt
# keys are mapped to ints by yaml loading,
#  so zero-filling here is not respected
01:
  - notebooks/lab01_pytorch.ipynb
  - text_recognizer/__init__.py
  - text_recognizer/data/util.py
  - text_recognizer/metadata/mnist.py
  - text_recognizer/metadata/shared.py
  - text_recognizer/models/__init__.py
  - text_recognizer/models/mlp.py
  - text_recognizer/util.py
02:
  - notebooks/lab02a_lightning.ipynb
  - notebooks/lab02b_cnn.ipynb
  - text_recognizer/data/__init__.py
  - text_recognizer/data/base_data_module.py
  - text_recognizer/data/emnist.py
  - text_recognizer/data/emnist_essentials.json
  - text_recognizer/data/emnist_lines.py
  - text_recognizer/data/mnist.py
  - text_recognizer/data/sentence_generator.py
  - text_recognizer/lit_models/__init__.py
  - text_recognizer/lit_models/base.py
  - text_recognizer/metadata/emnist.py
  - text_recognizer/metadata/emnist_lines.py
  - text_recognizer/models/cnn.py
  - text_recognizer/models/line_cnn_simple.py
  - text_recognizer/stems/image.py
  - training/__init__.py
  - training/run_experiment.py
  - training/util.py
03:
  - notebooks/lab03_transformers.ipynb
  - text_recognizer/data/iam.py
  - text_recognizer/data/iam_paragraphs.py
  - text_recognizer/lit_models/metrics.py
  - text_recognizer/lit_models/transformer.py
  - text_recognizer/lit_models/util.py
  - text_recognizer/metadata/iam.py
  - text_recognizer/metadata/iam_paragraphs.py
  - text_recognizer/models/resnet_transformer.py
  - text_recognizer/models/transformer_util.py
  - text_recognizer/stems/paragraph.py
04:
  - notebooks/lab04_experiments.ipynb
  - text_recognizer/callbacks/__init__.py
  - text_recognizer/callbacks/model.py
  - text_recognizer/callbacks/optim.py
  - text_recognizer/callbacks/util.py
  - text_recognizer/callbacks/imtotext.py
  - text_recognizer/data/iam_lines.py
  - text_recognizer/metadata/iam_lines.py
  - text_recognizer/models/line_cnn.py
  - text_recognizer/models/line_cnn_transformer.py
  - text_recognizer/stems/line.py
05:
  - .github/workflows/pre-commit.yml
  - .flake8
  - .pre-commit-config.yaml
  - notebooks/lab05_troubleshooting.ipynb
  - tasks/lint.sh
  - text_recognizer/data/fake_images.py
  - text_recognizer/tests/test_callback_utils.py
  - text_recognizer/tests/test_iam.py
  - training/tests/test_memorize_iam.sh
  - training/tests/test_run_experiment.sh
06:
  - notebooks/lab06_data.ipynb
  - text_recognizer/data/iam_original_and_synthetic_paragraphs.py
  - text_recognizer/data/iam_synthetic_paragraphs.py
  - text_recognizer/metadata/iam_synthetic_paragraphs.py
